modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="parse"
version="1.0.0"
displayName="Parse"
displayURL="https://github.com/WinterOverlord/Parse"
logoFile="logo.png"
credits="WinterOverlord"
authors="WinterOverlord"
description="Parse Mod"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.parse]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.parse]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration